### ISSUE TITLE
nKaruga port

### ISSUE THREAD

**Issue by gbbnfhb** [southoz/RetroOZ#56]
![nKaruga](https://user-images.githubusercontent.com/55620705/155851122-6b75d508-3923-4ca6-b68c-05cebd79f791.png)
https://mega.nz/file/AyBDFSYT#0RPy6Jc5sNG3ZLa1I1YQ9GWBAVJNirBSsR8Pix0qpY8

original:https://github.com/matrefeytontias/nKaruga

joypad & stick support
Other minor corrections

A -- FIRE
B -- POLARITY
X or L or R -- POWER
START -- PAUSE/CONTINUE
SELECT -- QUIT

**Comment by southoz** [comment]
Has this been included with portmaster? If not I can look at adding it in a future update.

**Comment by gbbnfhb** [comment]
sorry,I don't know how to use  portmaster
Since there is a source, only those who understand it should do it
I think it's easy because I only use sdl.
Test environment -- rgb10max

**Comment by southoz** [comment]
https://351elec.de/PortMaster is the list of ports under portmaster, I have been working with Johnny and Christian to support RetroOZ in more detail as I want to strip the supported ports from the base image due to having 1.2GB of themes and ports included. I will have a look in future of including portmaster rather than the individual ports.
